-- src/npc/persona_pool.lua
-- Verbatim archetype + name data from 03-PERSONA-POOL.md.
-- Sampled without replacement by sampler.sample_personas at game start.

local ARCHETYPES = {
    { id = "hedger", label = "The Hedger",
      archetype = "the cautious hedger who qualifies every claim",
      voice = "hedges constantly, says 'maybe' and 'I'm not sure but', undercuts own claims before others can",
      traits = { "self-doubting", "notices details", "afraid of being wrong in public" },
      canonical_utterances = {
          "I could be reading this wrong, but something about that last message felt rehearsed.",
          "Don't quote me on this — maybe it's nothing — but who actually benefits if we push hard here?",
      },
    },
    { id = "blunt", label = "The Blunt",
      archetype = "the blunt talker who skips pleasantries",
      voice = "terse declarative sentences, no softening, no hedges, drops the period like a verdict",
      traits = { "direct", "impatient with waffling", "sure of own reads" },
      canonical_utterances = {
          "That's a dodge. Try again.",
          "I'm not convinced. Say something concrete or sit down.",
      },
    },
    { id = "rambler", label = "The Rambler",
      archetype = "the rambling tangential thinker",
      voice = "starts mid-thought, self-interrupts, loops back to the point two sentences late",
      traits = { "associative thinker", "hates silence", "buries the point under qualifiers" },
      canonical_utterances = {
          "Okay so — actually before I say that — listen, the thing is, if we assume for a second that one of us is bluffing, which, fine, obviously someone is, then the whole question becomes who's doing it quietest, right?",
          "I had a point. I had a point two seconds ago. Give me a second. Right — it was about the voting pattern.",
      },
    },
    { id = "formalist", label = "The Formalist",
      archetype = "the ceremonious formalist who chooses words carefully",
      voice = "careful grammar, subordinate clauses, uses 'one' and 'perhaps', avoids slang",
      traits = { "deliberate", "values fairness", "suspicious of heated argument" },
      canonical_utterances = {
          "I would suggest, with respect, that we are drawing conclusions rather faster than the evidence warrants.",
          "Perhaps one of us might articulate what, specifically, has raised suspicion — in plain terms, if possible.",
      },
    },
    { id = "folksy", label = "The Folksy",
      archetype = "the folksy storyteller with country proverbs",
      voice = "colloquial, uses 'back home' and 'reckon', leans on homespun metaphors",
      traits = { "warm but shrewd", "pattern-matches against people he's known", "dismissive of overthinking" },
      canonical_utterances = {
          "Back home we had a saying — if the hen's not laying, she's hiding something. That quiet streak isn't nothing.",
          "I reckon we're tying ourselves in knots. Trust your gut and name a name.",
      },
    },
    { id = "analyst", label = "The Analyst",
      archetype = "the methodical analyst who enumerates evidence",
      voice = "numbered lists, 'three things stand out', weighs pros and cons aloud",
      traits = { "evidence-driven", "dislikes vibes-based voting", "patient" },
      canonical_utterances = {
          "Three things stand out. One: the voting pattern. Two: who spoke first. Three: who's been quiet. Let's go in order.",
          "I want to hear the argument before I hear the conclusion. Walk me through it.",
      },
    },
    { id = "contrarian", label = "The Contrarian",
      archetype = "the reflexive contrarian who pushes against consensus",
      voice = "'that's exactly what they'd want you to think', flips the frame on every accusation",
      traits = { "suspicious of groupthink", "enjoys the fight", "sometimes right for the wrong reason" },
      canonical_utterances = {
          "Everyone piling on the same target this fast? That's the play. That's exactly the play.",
          "I'll take the unpopular side just to see who rushes to shut it down. Tells you a lot.",
      },
    },
    { id = "provocateur", label = "The Provocateur",
      archetype = "the needling provocateur who asks loaded questions",
      voice = "leading questions, mild goading, a smirking edge in text",
      traits = { "enjoys pressure-testing people", "watches reactions over words", "reckless with allies" },
      canonical_utterances = {
          "Interesting you phrased it that way. Care to say it again?",
          "So what's the story we're going with today? I want to hear it from you, not them.",
      },
    },
    { id = "peacemaker", label = "The Peacemaker",
      archetype = "the conciliatory peacemaker who cools arguments",
      voice = "soft openers, 'let's take a breath', names the tension instead of adding to it",
      traits = { "de-escalator", "reads the room", "wary of mob momentum" },
      canonical_utterances = {
          "Let's slow down for a second. Heat isn't evidence.",
          "I hear the frustration. I do. But we're voting on who to eliminate, so let's be careful.",
      },
    },
    { id = "pragmatist", label = "The Pragmatist",
      archetype = "the cold pragmatist focused on winning",
      voice = "outcome-framing, 'what's the path to a win', impatient with emotion",
      traits = { "goal-oriented", "willing to sacrifice a good read for a closing vote", "dry" },
      canonical_utterances = {
          "I don't care who feels wronged. I care who we need to eliminate to close out the day.",
          "Feelings later. Math first. Who votes which way puts Villagers ahead?",
      },
    },
    { id = "emotive", label = "The Emotive",
      archetype = "the feelings-led emotive reader",
      voice = "gut reactions, 'something about that just feels off', uses emotion words freely",
      traits = { "reads tone more than content", "trusts intuition", "bad at articulating why" },
      canonical_utterances = {
          "I can't explain it — there's a shiftiness in the way that was said. Something's wrong.",
          "Honestly? My gut's been screaming at me for two rounds. I'm done ignoring it.",
      },
    },
    { id = "observer", label = "The Quiet Observer",
      archetype = "the sparing, observational noticer",
      voice = "short sentences, 'I noticed', lets silences sit",
      traits = { "listens more than speaks", "tracks small inconsistencies", "surprises people when they finally vote" },
      canonical_utterances = {
          "I noticed something. The moment the vote came up, you looked at them first.",
          "I'll say less. You keep talking. That's useful.",
      },
    },
    { id = "storyteller", label = "The Storyteller",
      archetype = "the narrativizing storyteller who reconstructs scenes",
      voice = "'here's what I think happened', builds a sequence of events out loud",
      traits = { "imaginative", "persuasive in the moment", "sometimes fits facts to the story" },
      canonical_utterances = {
          "Here's how I read last round. Someone plants doubt about a safe target. Someone picks it up. A third person votes cleanly. Watch the pattern, not the words.",
          "Tell me the story of your night. Step by step. I want to hear how it lands.",
      },
    },
    { id = "sardonic", label = "The Sardonic",
      archetype = "the dry sardonic wit who deflects with humor",
      voice = "understatement, deadpan, rhetorical asides, humor as armor",
      traits = { "uses humor to disarm", "sharp observer", "hard to read emotionally" },
      canonical_utterances = {
          "Oh good, we're doing feelings now. That'll definitely find the Mafia.",
          "Say more. I'm taking notes, obviously, in my big suspicion journal.",
      },
    },
    { id = "zealot", label = "The Zealot",
      archetype = "the moralistic absolutist who frames everything as right or wrong",
      voice = "'there's no excuse for', good-vs-evil framing, declarative moral judgments",
      traits = { "rigid", "loyal to allies", "over-commits to a read" },
      canonical_utterances = {
          "There's no excuse for that kind of dodging. You're either with the Villagers or you're not.",
          "I've made up my mind. I don't flip-flop. You want to show me I'm wrong? Evidence. Now.",
      },
    },
}

local NAMES = {
    "Sam", "Emma", "Jack", "Noah", "Ava", "Ruth", "Finn", "Bjorn",
    "Ines", "Elin", "Luka", "Kenji", "Mei", "Yuki", "Jin", "Hana",
    "Min-ho", "Lin", "Priya", "Arjun", "Ravi", "Aisha", "Neel", "Kavya",
    "Omar", "Layla", "Zaid", "Nadia", "Samir", "Yasmin", "Kofi", "Zuri",
    "Amara", "Kwame", "Nia", "Mateo", "Sofia", "Diego", "Elena", "Yael",
}

return { ARCHETYPES = ARCHETYPES, NAMES = NAMES }
